# Generated by Django 4.0.1 on 2022-01-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_bio_remove_profile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='profile_images/'),
        ),
    ]
